### ISSUE TITLE
Endless Loop when Displaying List

### ISSUE THREAD

**Issue by JacksonSavvy** [Lyxica/Miles-10-Sound-Dumper#1]
When I try the command:
MSD -l                                  -- Display list of all event IDs and names contained in audio files
I seem to get an endless loop on the first event
![loop](https://user-images.githubusercontent.com/52832758/61146062-ae71ea80-a49e-11e9-8213-7d299fbbea51.jpg)

**Comment by aaaaaaaaaaaaaaaaaxaaaaaa** [comment]
Strange, to make sure, the command you're typing into command prompt looks like this?
![image](https://user-images.githubusercontent.com/51021389/61160837-fb14f000-a4b5-11e9-8af6-fdf1f5cb0e6b.png)

**Comment by JacksonSavvy** [comment]
Well, upon an update to Apex and a reboot, worked fine.  Very strange.  Thank you, sir
