### ISSUE TITLE
couldn't find a usable routing matrix

### ISSUE THREAD

**Issue by Kyr4l** [Lyxica/Miles-10-Sound-Dumper#3]
![image](https://user-images.githubusercontent.com/24955106/61191714-e69b4800-a6ad-11e9-9d05-233fb92f8b7e.png)

**Comment by mafima** [comment]
id: 22132
name: Music_Sample_Event1

**Comment by aaaaaaaaaaaaaaaaaxaaaaaa** [comment]
These messages pop up but don't seem to cause any issues in the actual playback of the event. I would guess they're errors in the file itself that don't matter.

**Comment by Kyr4l** [comment]
the problem is that when i get this error, the extracted file is only 1kB

**Comment by aaaaaaaaaaaaaaaaaxaaaaaa** [comment]
I've just fixed that in 06d4a754c3c00729635f97506bfc56ee73462548

**Comment by Kyr4loO** [comment]
> 
> 
> I've just fixed that in [06d4a75](https://github.com/Lyxica/Miles-10-Sound-Dumper/commit/06d4a754c3c00729635f97506bfc56ee73462548)

thank for fixing it, but now i'm havin the same error with this one
![image](https://user-images.githubusercontent.com/24955106/61255404-ba90cd00-a768-11e9-86b6-55c1e316e6e4.png)
