### ISSUE TITLE
noise level issues

### ISSUE THREAD

**Issue by mafima** [Lyxica/Miles-10-Sound-Dumper#4]
Command: msd 16549 16554
issue: wrong audiofile recording
caused by: sounds with silent middlepart. can noise level fix this?
what i tried: 
msd 16549 16554 --noise=0 
result: first sound is playing, but no recording and cant end recording with ESC

**Comment by aaaaaaaaaaaaaaaaaxaaaaaa** [comment]
Can you give me the specific event name you're having issues with? The numbers seem to vary by region.

> and cant end recording with ESC

Fixed in 46f2e94c83d4a44cb7eee71613d464c2b138edae
