### ISSUE TITLE
cannot dump some songs

### ISSUE THREAD

**Issue by Kyr4l** [Lyxica/Miles-10-Sound-Dumper#5]
i know some songs are just impossible to dump because they com from titanfall 2 and aren't actually in the game files
but this one is in the game files, and was used some month ago
![image](https://user-images.githubusercontent.com/24955106/61303929-9f65a200-a7e8-11e9-938d-1adfc195949d.png)

**Comment by aaaaaaaaaaaaaaaaaxaaaaaa** [comment]
This was fixed in the v1.0-beta4 release.

**Comment by Kyr4l** [comment]
so why am i unable to dump this one ?

**Comment by aaaaaaaaaaaaaaaaaxaaaaaa** [comment]
Try the v1.0-beta5 release. It should work now. If you find any other sounds that don't record,  check if they play when you run MSD by itself (not dumping). If they play but don't record, try adjusting the 2 new flags I've added (--start and --end), just set their values higher.

**Comment by Kyr4l** [comment]
looks like it's working now, thanks
